[main]

[[main.block]]
format = "html"
content_file = "input/global/elements/head.html"

[[main.block]]
format = "html"
content_file = "input/pages/contact/head.html"

[[main.block]]
format = "html"
content_file = "input/global/elements/navbar.html"

[[main.block]]
format = "md"
content_file = "input/pages/contact/contact.md"

[[main.block]]
format = "html"
content_file = "input/global/elements/footer.html"
